// src/app/sidebar/sidebar.component.ts
import { Component } from '@angular/core';

interface SidebarItem {
  title: string;
  icon: string;
  link: string;
  class?: string;
}

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent {

  items: SidebarItem[] = [
    {
      icon: '/assets/sidebar/Arrow.svg',
      title: 'FloatingComet62',
      class: 'arrow',
      link: '/'
    },
    {
      icon: '/assets/sidebar/Home.svg',
      title: 'Home',
      link: '/'
    },
    {
      icon: '/assets/sidebar/Projects.svg',
      title: 'Projects',
      link: '/projects'
    },
    {
      icon: '/assets/sidebar/About me.svg',
      title: 'About me',
      link: '/about'
    },
    {
      icon: '/assets/sidebar/Contact.svg',
      title: 'Contact',
      class: 'contact',
      link: '/contact'
    }
  ]

  goto(link: string){
    location.href = link;
  }

}

<div id=navbar>
  <div class="{{ item.class ? 'item '+item.class : 'item' }}" *ngFor="let item of items" (click)="goto(item.link)">
    <img src="{{ item.icon }}" alt="{{ item.title }}" width="50" height="50">
    <span>{{ item.title }}</span>
</div>
</div>

// components/sidebar.tsx
import styles from '@cstyles/sidebar.module.scss'
import Image from 'next/image'

interface SidebarItem {
    title: string
    icon: string
    link: string
    class?: string
}

export default function sidebar() {
    const items: SidebarItem[] = [
        {
            icon: '/sidebar/Arrow.svg',
            title: 'FloatingComet62',
            class: 'arrow',
            link: '/'
        },
        {
            icon: '/sidebar/Home.svg',
            title: 'Home',
            link: '/'
        },
        {
            icon: '/sidebar/Projects.svg',
            title: 'Projects',
            link: '/projects'
        },
        {
            icon: '/sidebar/About me.svg',
            title: 'About me',
            link: '/about'
        },
        {
            icon: '/sidebar/Contact.svg',
            title: 'Contact',
            class: 'contact',
            link: '/contact'
        }
    ]

    return (
        <div className={ styles.navbar }>
            {  items.map((item) => {
                return (
                    <>
                    <div className={ item.class ? styles.item + " " + styles[item.class] : styles.item } key={ item.title } onClick={() => location.href=item.link}>
                        <Image className={ item.class ? styles[item.class+"image"]: '' } src={ item.icon } alt={ item.title } width={50} height={50} />
                        <div className={ styles.text }>{ item.title }</div>
                    </div>
                    </>
                )
                })
            }
        </div>
    )
}
