// pages/_app.tsx
import '@style/font.scss'
import '@style/global.scss'
import { AppProps } from 'next/app'

import Sidebar from '@c/sidebar'
import Image from 'next/image'

export default function App({ Component, pageProps }: AppProps) {
  const random = Math.round(Math.random() * 19 + 1 )

  return (
  <>
  <Image style={{filter: "opacity(0.5)"}} src={`/backgrounds/${random}.png`} alt={'background'} layout="fill" />
  <Component {...pageProps} />
  <Sidebar />
  </>
  )
}

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  title = 'FloatingComet62';
  random = `${1+Math.round(Math.random() * 19)}`;

}

<img alt="background" id="bg" src="/assets/backgrounds/{{ random }}.png" />
<router-outlet class="main"></router-outlet>
<app-sidebar></app-sidebar>
