// src/app/projects/projects.component.ts
import { Component, OnInit } from '@angular/core';
import LanyardResponse from '../../Lanyard';

interface Projects{
  title: string;
  description: string;
  tryLink: string;
  codeLink: string;
  image: string;
}

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent implements OnInit {

  Projects: Projects[] = [
    {
      title: 'PainScript',
      description: 'A programming language pain to code in and inspired by brainf**k.',
      tryLink: 'https://github.com/FloatingComet62/PainScript/releases/tag/v1.1.0',
      codeLink: 'https://github.com/FloatingComet62/PainScript',
      image: '/assets/projects/PainScript.png'
    },
    {
      title: 'UniverseSafe',
      description: 'A discord bot that will help you keep your server safe',
      tryLink: 'https://github.com/FloatingComet62/UniverseSafe',
      codeLink: 'https://github.com/FloatingComet62/UniverseSafe',
      image: '/assets/projects/UniverseSafe.png'
    },
    {
      title: 'RealBox',
      description: 'My First Game. (Yes it is very bad)',
      tryLink: 'https://floatingcomet62.github.io/Real-box/',
      codeLink: 'https://github.com/FloatingComet62/Real-Box',
      image: '/assets/projects/RealBox.png'
    },
    {
      title: 'Enver',
      description: 'An env editor as a donwloadable npm package',
      tryLink: 'https://www.npmjs.com/package/handle-env',
      codeLink: 'https://github.com/FloatingComet62/enver',
      image: '/assets/projects/Enver.png'
    },
    {
      title: 'Hashing API',
      description: 'A simple hashing API',
      tryLink: 'https://hashing-api-production.up.railway.app/',
      codeLink: 'https://github.com/FloatingComet62/Hashing-API',
      image: '/assets/projects/HashingAPI.png'
    },
    {
      title: 'FluidDB',
      description: 'Fluid DB is a no-sql database service',
      tryLink: '',
      codeLink: 'https://github.com/FloatingComet62/FluidDB',
      image: '/assets/projects/FluidDB.png'
    },
    {
      title: 'PrimeFinder',
      description: 'A prime number finder',
      tryLink: 'https://github.com/FloatingComet62/PrimeFinder/releases/tag/v1',
      codeLink: 'https://github.com/FloatingComet62/PrimeFinder',
      image: '/assets/projects/PrimeFinder.png'
    },
    {
      title: 'Chess',
      description: 'A chess game in your command line',
      tryLink: '',
      codeLink: 'https://github.com/FloatingComet62/Chess',
      image: '/assets/projects/Chess.png'
    }
  ]

  Discordstatus = 'Loading';
  current = 0;

  constructor() { }

  ngOnInit(): void {
    setInterval(async ()=>{
      await this.updateInfo();
    }, 1000);
  }

  async updateInfo(): Promise<void> {
    const response: LanyardResponse = await (await fetch('https://api.lanyard.rest/v1/users/701059544574591006')).json();
    if(!response.success) return;
    
    const status = response.data.discord_status;
    if(status=='dnd') this.Discordstatus = 'DnD';
    else if(status=='online') this.Discordstatus = 'Online';
    else if(status=='idle') this.Discordstatus = 'Idle';
    else if(status=='offline') this.Discordstatus = 'Offline';
  }

  goto(link: string){
    if(link!='') location.href = link;
  }

  switch(direction: boolean){
    if(direction){
      this.current++;
      if(this.current>=this.Projects.length) this.current = 0;
    }else{
      this.current--;
      if(this.current<0) this.current = this.Projects.length-1;
    }
  }

}
<div id="body">
    <div id="title">Actual Good Content I make</div>
    <img id="discord" src='/assets/discord/{{ Discordstatus }}.svg' alt="{{ Discordstatus }}" width="50" height="50" />
    <div id="projects">
        <div class="mover" (click)="switch(false)">
            <img src="/assets/ProjectArrow.svg" alt="Arrow" class="arrow left" width="40" height="40">
        </div>
        <div id="project">
            <div id="projectTitle">{{ Projects[current].title }}</div>
            <div id="description">
                <div id="info">{{ Projects[current].description }}</div>
                <img src="{{ Projects[current].image }}" alt="Logo" id="logo" width="200" height="200">
            </div>
            <div id="buttons">
                <div class="button" (click)="goto(Projects[current].tryLink)">Try It</div>
                <div class="button" (click)="goto(Projects[current].codeLink)">Source Code</div>
            </div>
        </div>
        <div class="mover" (click)="switch(true)">
            <img src="/assets/ProjectArrow.svg" alt="Arrow" class="arrow right" width="40" height="40">
        </div>
    </div>
</div>

// pages/projects.tsx
import styles from '@pstyles/projects.module.scss'
import Image from 'next/image'
import { useState } from 'react'
import { Projects, lanyard } from 'public/dry'

function goto(link: string) {
    if (link!='') location.href = link;
}

export default function Home({ projects, discord }: { projects: Projects[], discord: string }) {
    const [ current, setCurrent ] = useState<number>(0);

    function change(direction: boolean) {
        if (direction) {
            if (current+1>=projects.length) setCurrent(0);
            else setCurrent(current + 1);
        } else {
            if (current<1) setCurrent(projects.length-1)
            else setCurrent(current - 1);
        }
    }
    
    return (
    <>
    <div className={ styles.body }>
    <div className={ styles.head }>
      <div></div>
      <div className={ styles.title }>Actual Good Content I make</div>
      <Image className={ styles.discord } src={`/discord/${ discord }.svg`} alt={ discord } width={50} height={50} />
    </div>
    <div className={ styles.projects }>
        <div className={ styles.mover } onClick={ () => change(false) } >
            <Image src="/ProjectArrow.svg" alt="Arrow" className={`${ styles.arrow } ${ styles.left }`} width={40} height={40} />
        </div>
        <div className={ styles.project }>
            <div className={ styles.projectTitle }>{ projects[current].title }</div>
            <div className={ styles.description }>
                <div className={ styles.info }>{ projects[current].description }</div>
                <Image src={ projects[current].image } alt="Logo" id="logo" width={200} height={200} />
            </div>
            <div className={ styles.buttons }>
                <div className={ styles.button } onClick={ () => goto(projects[current].tryLink) }>Try It</div>
                <div className={ styles.button } onClick={ () => goto(projects[current].codeLink) }>Source Code</div>
            </div>
        </div>
        <div className={ styles.mover } onClick={ () => change(true) }>
            <Image src="/ProjectArrow.svg" alt="Arrow" className={`${ styles.arrow } ${ styles.right }`} width={40} height={40} />
        </div>
    </div>
    </div>
    </>
    )
}

export async function getServerSideProps() {
  const projects: Projects[] = [
        {
          title: 'PainScript',
          description: 'A programming language pain to code in and inspired by brainf**k.',
          tryLink: 'https://github.com/FloatingComet62/PainScript/releases/tag/v1.1.0',
          codeLink: 'https://github.com/FloatingComet62/PainScript',
          image: '/projects/PainScript.png'
        },
        {
          title: 'UniverseSafe',
          description: 'A discord bot that will help you keep your server safe',
          tryLink: 'https://github.com/FloatingComet62/UniverseSafe',
          codeLink: 'https://github.com/FloatingComet62/UniverseSafe',
          image: '/projects/UniverseSafe.png'
        },
        {
          title: 'RealBox',
          description: 'My First Game. (Yes it is very bad)',
          tryLink: 'https://floatingcomet62.github.io/Real-box/',
          codeLink: 'https://github.com/FloatingComet62/Real-Box',
          image: '/projects/RealBox.png'
        },
        {
          title: 'Enver',
          description: 'An env editor as a donwloadable npm package',
          tryLink: 'https://www.npmjs.com/package/handle-env',
          codeLink: 'https://github.com/FloatingComet62/enver',
          image: '/projects/Enver.png'
        },
        {
          title: 'Hashing API',
          description: 'A simple hashing API',
          tryLink: 'https://hashing-api-production.up.railway.app/',
          codeLink: 'https://github.com/FloatingComet62/Hashing-API',
          image: '/projects/HashingAPI.png'
        },
        {
          title: 'FluidDB',
          description: 'Fluid DB is a no-sql database service',
          tryLink: '',
          codeLink: 'https://github.com/FloatingComet62/FluidDB',
          image: '/projects/FluidDB.png'
        },
        {
          title: 'PrimeFinder',
          description: 'A prime number finder',
          tryLink: 'https://github.com/FloatingComet62/PrimeFinder/releases/tag/v1',
          codeLink: 'https://github.com/FloatingComet62/PrimeFinder',
          image: '/projects/PrimeFinder.png'
        },
        {
          title: 'Chess',
          description: 'A chess game in your command line',
          tryLink: '',
          codeLink: 'https://github.com/FloatingComet62/Chess',
          image: '/projects/Chess.png'
        }
  ]
  const data = await lanyard()
  return {
    props: {
      projects: projects,
      discord: data.discord
    }
  }
}
